# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: realtime_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13realtime_data.proto\x12\rrealtime_data\"\x15\n\x13RealTimeDataRequest\"$\n\x14RealTimeDataResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2k\n\x13RealTimeDataService\x12T\n\x07GetData\x12\".realtime_data.RealTimeDataRequest\x1a#.realtime_data.RealTimeDataResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'realtime_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_REALTIMEDATAREQUEST']._serialized_start=38
  _globals['_REALTIMEDATAREQUEST']._serialized_end=59
  _globals['_REALTIMEDATARESPONSE']._serialized_start=61
  _globals['_REALTIMEDATARESPONSE']._serialized_end=97
  _globals['_REALTIMEDATASERVICE']._serialized_start=99
  _globals['_REALTIMEDATASERVICE']._serialized_end=206
# @@protoc_insertion_point(module_scope)
